### ISSUE TITLE
adding option to disable verifying the SSL certificate

### ISSUE THREAD

**Issue by spyj-1989** [UNSW-CEEM/nempy#11]
Hello Nick,

Would you please add the optionality to disable verifying the SSL certificate in requests.get() method, i.e. verify=False, in functions like _download_xml_from_nemweb in xml_cache.py file?

Thank you.

**Comment by nick-gorman** [comment]
Hi @spyj-1989 

I haven't run into any issues with this function. Can you please provide some details on the issue you're having, why you want this featured added?

Cheers,
Nick

**Comment by spyj-1989** [comment]
Hello Nick,

How are you? Thank you for replying to my query.

By implementing your example code I'm getting the following error:

[image: image.png]

The verification issue shouldn't be a problem for personal or academic
networks but for some commercial IT environments, an option to turn off the
verification, i.e. verify = False, is needed in order to avoid
going through the IT process to properly resolve the SSL certificate
verification issue.

Hope you could help add the small feature into your package.

Best regards,

Can Jin

**Comment by dehorsley** [comment]
I think a preferable solution to this, and using `requests` behind a corporate firewall in general, is to use the system certificate store, assuming your IT department has added their firewall's root certificate to your system's store. This can be done with [pip-system-certs](https://pypi.org/project/pip-system-certs/) (this also works with `requests` despite its name)

**Comment by nick-gorman** [comment]
@dehorsley this sounds like a good solution.

Also, as it appears there are other workarounds (https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests), I think it's easiest not to implement this for now. Also, this avoids taking Nempy down the road of managing security issues.

@spyj-1989 If neither of these work and this is an ongoing problem please feel free to reopen this issue.
