### ISSUE TITLE
XMLCacheManager.populate_by_day

### ISSUE THREAD

**Issue by dec-heim** [UNSW-CEEM/nempy#13]
Hey @nick-gorman, very minor here but..

`populate_by_day` in XMLCacheManager seems to break if you pass end_month=12

https://github.com/UNSW-CEEM/nempy/blob/73609a0552eff1a0dc500f9d5b9d94f40eca0f9c/nempy/historical_inputs/xml_cache.py#L47-L54

I think what's intended is...
```
if (end_month == 12) & (end_day == 31):
    end_day = 1
    end_month = 1
    end_year += 1
```

**Comment by nick-gorman** [comment]
Thanks @dec-heim,

Yep, that definitely looks wrong, I think we might actually be able to get rid of that if statement altogether, doesn't look to be doing anything useful.

Any thoughts?

**Comment by nick-gorman** [comment]
Fixed with release: https://github.com/UNSW-CEEM/nempy/releases/tag/v1.1.6
