### ISSUE TITLE
Add Very Fast Contingency FCAS constraints

### ISSUE THREAD

**Issue by mlee94** [UNSW-CEEM/nempy#19]
Market implementation change added: RAISE1SEC (R1) and LOWER1SEC (L1) to the FCAS NEMDE Model. This went live Monday 9 October 2023 at 1.00pm (Market Time).

From AEMO's update to the FCAS [model](https://aemo.com.au/-/media/files/electricity/nem/security_and_reliability/dispatch/policy_and_process/fcas-model-in-nemde.pdf?la=en), these services will constrain FCAS availability in the same manner as the existing raise and lower contingency services.

**Comment by nick-gorman** [comment]
Closed with PR #20
