### ISSUE TITLE
Looks like plotly is missing in your requirements?

### ISSUE THREAD

**Issue by nick-gorman** [UNSW-CEEM/nempy#5]
Thanks! Now it works. So you need to add pytest 6.2.5 to your requirements?

Next problem:

(nempyenv) C:\work\nempy\nempy\examples>python all_features_example.py
Traceback (most recent call last):
  File "C:\work\nempy\nempy\examples\all_features_example.py", line 5, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'

Looks like plotly is missing in your requirements?

_Originally posted by @noah80 in https://github.com/UNSW-CEEM/nempy/issues/4#issuecomment-981487839_

**Comment by nick-gorman** [comment]
Plotly is deliberately left out of the requirements because its not needed to run nempy. 

It's just being used with nempy in this particular example.

You should be able to get the example running, with a simple `pip install plotly`

**Comment by noah80** [comment]
Yes, I'm aware how to install plotly manually, thanks. :)

My point was that my understanding of the review includes checking that the examples work. And if the attempt to run the examples fails from lacking packages then that's not optimal. Shouldn't the dev requirements at least include everything you need to run the examples?

kaleido is missing too from the requirements by the way.

One suggestion regarding the all_features_examples: Maybe add a check if the file is already downloaded so that the user doesn't have to manually edit the code?

**Comment by nick-gorman** [comment]
Hi @noah80, I see your point about the examples not working out of the box.

I'm reluctant to fix the issue by adding plotly and kaleido to the dev requirements as this doesn't fix the problem for users who just do the simple pip install nempy, and adding extra requirements is more likely to lead to dependencies conflicts. 

Instead I've now added inline comments to the examples detailing the extra requirements, and the versions to install. I've also added a note box to the documentation to highlight these extra dependencies. See link:
https://nempy.readthedocs.io/en/latest/examples.html#detailed-recreation-of-historical-dispatch

What do you think about this approach?

Regarding the check for files already downloaded, this has issues where the data might be partially downloaded, and the download gets interrupted, say due to network issues or by the use interrupting the script. In this case in a subsequent run of the example the check for data would pass, and then the script would fail later, potentially with a confusing error. 

If the user has to explicitly skip the download I think there is less chance of this happening, and if it does the fix (resetting the flag to download the data) is simpler and more obvious to the user. 

Ideally, nempy would include a more sophisticated data check that would manage all of this, but that's a bit complicated and I haven't had the chance to implement it.
